[tool.black]
line-length = 160

[tool.ruff]
line-length = 160
target-version = "py312"

[tool.docformatter]
wrap-summaries = 80
wrap-descriptions = 80
pre-summary-newline = false
make-summary-multi-line = false
close-quotes-on-newline = false
